// UNDERSTAND
/*
q = [2, 1, 5, 3, 4]
Answer = 3

q = [2, 5, 1, 3, 4]
Answer = Too chaotic

- SWAPS ONLY HAPPEN STARTING FROM THE RIGHT SIDE OF THE ARRAY
- CAN NOT GO BACK THROUGH ARRAY AGAIN
- CAN ONLY SWAP TWICE

EDGE CASES:
- ARE THERE MULTIPLE WAYS TO SWAP?

*/

// PLAN
/*
CREATE A VARIABLE CALLED SWAP TO COUNT THE NUMBER OF SWAPS THAT TOOK PLACE

LOOP BACKWARDS??
FIND THE OUT OF PLACE ELEMENT
[1, 2, 3, 4, 5] VS. [2, 1, 5, 3, 4]
IF CURRENT ELEMENT IS OUT OF PLACE:
SWAP RIGHT TO LEFT UNTIL ELEMENT IS IN ITS NEW PLACE
EXAMPLE:
ORIGINAL[4 + 1] = ORIGINAL[4]
ORIGINAL[4] = ORIGINAL[4 + 1]

ELSE:
MOVE TO NEXT INDEX
*/

// EXECUTE
function minimumBribes(q) {


}